prefix ?= /usr/local
exec_prefix := ${prefix}
libdir := ${exec_prefix}/lib
datarootdir := ${prefix}/share
datadir := ${datarootdir}
includedir := ${prefix}/include

abs_top_srcdir ?= $(abspath $(TOP))
abs_top_builddir = $(abspath $(TOP))
SUBDIR = $(patsubst /%,%,$(subst $(abs_top_builddir)/src,,$(CURDIR)))
srcdir = $(patsubst %/,%,$(abs_top_srcdir)/src/$(SUBDIR))

INSTALL := install

LIBELF_CFLAGS = $(shell pkg-config --cflags libelf)
LIBELF_LIBS = $(shell pkg-config --libs libelf)
